### ISSUE TITLE
Authenticate Middleware Redirect to default login page

### ISSUE THREAD

**Issue by mithicher** [team-underground/flowcms#3]
After session timeout it tries to redirect to ```/login``` page but Laravel tries to find the template in default path:
```
/resource/auth/login.blade.php
```

instead of the flowcms login path.

Suggestion as given below

```php
<?php

namespace App\Http\Middleware;

use Illuminate\Auth\Middleware\Authenticate as Middleware;

class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return string|null
     */
    protected function redirectTo($request)
    {
        if (! $request->expectsJson()) {
            // return route('login');
            return route('flowcms::login');
        }
    }
}
```

**Comment by abhisheksarmah** [comment]
- add a new middleware named `AuthenticateWithFlowcms` in flowcms namespace which extends `Illuminate\Auth\Middleware\Authenticate`
- register the middleware group as `auth.flowcms` in the kernel through `FlowcmsServiceProvider`
- change the `auth` middleware to `auth.flowcms` in the `web.php`
